# Generated by Django 4.2.4 on 2023-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name'),
        ),
    ]
