# Generated by Django 4.2.4 on 2023-09-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
